/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.aeo.memeory.gk_in_22_memory.git.trunk.memeorybrettAnt.memeory.src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Sonia
 */
public class BrettMitEinBisschenVerzweiflung extends javax.swing.JFrame implements ActionListener{

    private ArrayList<JButton> knopfe =new ArrayList<>();
    /**
     * Creates new form BrettMitEinBisschenVerzweiflung
     */
    public BrettMitEinBisschenVerzweiflung() {
        erstelleKnopfe(4,5);
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // Merksatz:
    //Zeilen zu erst, Spalten später!
    private void erstelleKnopfe(int a,int b){ 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(770, 650));
        setMinimumSize(new java.awt.Dimension(750, 630));
        setPreferredSize(new java.awt.Dimension(767, 637));
        setSize(new java.awt.Dimension(767, 637));
        getContentPane().setLayout(null);
        int z = 0;
        int zz=a*b;
        while (z<zz){
            knopfe.add(new javax.swing.JButton());
            getContentPane().add(knopfe.get(z));
            z=z+1;
        }
        z=0;
        while (z<a){
            zz=0;
            while (zz<b){
                System.out.println("("+zz*150+","+z*150+")");
                knopfe.get(z).setBounds(zz*150, z*150, 150, 150);
                System.out.println("Nr. "+(z*5+zz)+knopfe.get(z).getLocation() );
                zz=zz+1;
            }
            z=z+1;
        }
        z=a*b;
        while (z>0){
            z=z-1;
            knopfe.get(z).addActionListener(this);
            System.out.println("ich bin Nr. "+z+" auf" + knopfe.get(z).getLocation());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(770, 650));
        setMinimumSize(new java.awt.Dimension(750, 630));
        setPreferredSize(new java.awt.Dimension(767, 637));
        setSize(new java.awt.Dimension(767, 637));
        getContentPane().setLayout(null);

        jButton2.setText("B1");
        jButton2.setActionCommand("6");
        jButton2.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 150, 150, 150);

        jButton3.setText("A1");
        jButton3.setActionCommand("1");
        jButton3.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton3.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 150, 150);

        jButton4.setText("A2");
        jButton4.setActionCommand("2");
        jButton4.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton4.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton4.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 0, 150, 150);

        jButton5.setText("A3");
        jButton5.setActionCommand("3");
        jButton5.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton5.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 0, 150, 150);

        jButton6.setText("A4");
        jButton6.setActionCommand("4");
        jButton6.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton6.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton6.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 0, 150, 150);

        jButton7.setText("B2");
        jButton7.setActionCommand("7");
        jButton7.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton7.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton7.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(150, 150, 150, 150);

        jButton8.setText("B3");
        jButton8.setActionCommand("8");
        jButton8.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton8.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton8.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(300, 150, 150, 150);

        jButton9.setText("B4");
        jButton9.setActionCommand("9");
        jButton9.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton9.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton9.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(450, 150, 150, 150);

        jButton10.setText("B5");
        jButton10.setActionCommand("10");
        jButton10.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton10.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton10.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(600, 150, 150, 150);

        jButton11.setText("jButton2");
        jButton11.setActionCommand("11");
        jButton11.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton11.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton11.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(0, 300, 150, 150);

        jButton12.setText("jButton2");
        jButton12.setActionCommand("12");
        jButton12.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton12.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton12.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(150, 300, 150, 150);

        jButton13.setText("jButton2");
        jButton13.setActionCommand("13");
        jButton13.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton13.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton13.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(300, 300, 150, 150);

        jButton14.setText("A5");
        jButton14.setActionCommand("5");
        jButton14.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton14.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton14.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(600, 0, 150, 150);

        jButton15.setText("jButton2");
        jButton15.setActionCommand("15");
        jButton15.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton15.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton15.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(600, 300, 150, 150);

        jButton16.setText("jButton2");
        jButton16.setActionCommand("16");
        jButton16.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton16.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton16.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(0, 450, 150, 150);

        jButton17.setText("jButton2");
        jButton17.setActionCommand("17");
        jButton17.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton17.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton17.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(150, 450, 150, 150);

        jButton18.setText("jButton2");
        jButton18.setActionCommand("18");
        jButton18.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton18.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton18.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(300, 450, 150, 150);

        jButton19.setText("jButton2");
        jButton19.setActionCommand("19");
        jButton19.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton19.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton19.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(450, 450, 150, 150);

        jButton20.setText("jButton2");
        jButton20.setActionCommand("20");
        jButton20.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton20.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton20.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(600, 450, 150, 150);

        jButton21.setText("jButton2");
        jButton21.setActionCommand("14");
        jButton21.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton21.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton21.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(450, 300, 150, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrettMitEinBisschenVerzweiflung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrettMitEinBisschenVerzweiflung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrettMitEinBisschenVerzweiflung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrettMitEinBisschenVerzweiflung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrettMitEinBisschenVerzweiflung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("Ein Knopf wurde gedrückt.");
    }
}
